# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "成果一览"
  pageRef = "Lau-Joe-Academic-Achievements"
  weight = 10
  params = { icon = "study" }

[[main]]
  name = "学术论文"
  pageRef = "Article"
  weight = 20
  params = { icon = "article" }

[[main]]
  name = "报刊文章"
  pageRef = "Newspaper"
  weight = 30
  params = { icon = "newspaper" }

[[main]]
  name = "简历"
  pageRef = "CV"
  weight = 40
  params = { icon = "cv" }

[[main]]
  name = "回顾与总结"
  pageRef = "Review-summary"
  weight = 50
  params = { icon = "Review-summary" }

[[main]]
  name = "Soar Freely 博客"
  weight = 60
  url = "https://www.laujoe.top"
  params = { icon = "blog" }

[[main]]
  identifier = "search"
  weight = 60
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
