# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "Lau Joe's CV"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

defaultThemeColor = "#FFFFFF"

enableSearch = false
enableCodeCopy = false
enableImageLazyLoading = true
enableImageWebp = true

# robots = ""
fingerprintAlgorithm = "sha256"

[header]
  layout = "basic" # valid options: basic, hamburger, hybrid, custom
  # logo = "img/logo.jpg"
  # logoDark = "img/dark-logo.jpg"
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, custom
  showRecent = false
  recentLimit = 2

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = false
  showComments = false
  # sharingLinks = ["facebook", "x-twitter", "mastodon", "pinterest", "reddit", "linkedin", "email", "threads", "telegram", "line", "weibo", "xing", "bluesky"]

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  showTaxonomies = false
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"

[plausibleAnalytics]
  # domain = "blog.yoursite.com"
  # event = ""
  # script = ""

#[umamiAnalytics]
#  site = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#  region = "us"  # can be either "eu" or "us"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[author]
  name = "Lau Joe"  # 显示的大标题名字
  image = "author.jpg" # (请把照片放入 assets/ 文件夹)
  headline = "Ph.D. Student / Python Developer" # 你的头衔
  bio = "这里写你的个人简介。例如：Focusing on academic tools development." # 简介
  
  # 下面配置你的社交链接 (按需增删)
  [[author.links]]
    icon = "github"
    href = "https://github.com/laujoe"
  
  [[author.links]]
    icon = "email" # 对应 mail 图标
    href = "mailto:your-email@example.com"

  [[author.links]]
    icon = "graduation-cap" # 学术帽图标，适合放 Google Scholar
    href = "https://scholar.google.com/..."
