# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

[params.header]
  # å¿…é¡»åŠ ä¸Šè¿™ä¸€è¡Œï¼Œå³ä¸Šè§’æ‰ä¼šå‡ºç° ğŸŒ/ğŸŒ™ å›¾æ ‡
  showAppearanceSwitcher = true

defaultThemeColor = "#504747"

enableSearch = true
enableCodeCopy = false
enableImageLazyLoading = true
enableImageWebp = true

# robots = ""
fingerprintAlgorithm = "sha256"

[header]
  layout = "basic" # valid options: basic, hamburger, hybrid, custom
  # logo = "img/logo.jpg"
  # logoDark = "img/dark-logo.jpg"
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, custom
  showRecent = false
  recentLimit = 2

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = false
  showComments = false
  # sharingLinks = ["facebook", "x-twitter", "mastodon", "pinterest", "reddit", "linkedin", "email", "threads", "telegram", "line", "weibo", "xing", "bluesky"]

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  showTaxonomies = true
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"

[plausibleAnalytics]
  # domain = "blog.yoursite.com"
  # event = ""
  # script = ""

#[umamiAnalytics]
#  site = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#  region = "us"  # can be either "eu" or "us"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[author]
  name = "Lau Joe"  # æ˜¾ç¤ºçš„å¤§æ ‡é¢˜åå­—
  image = "author.jpg" # (è¯·æŠŠç…§ç‰‡æ”¾å…¥ assets/ æ–‡ä»¶å¤¹)
  headline = "Ph.D. Student / Python Developer" # ä½ çš„å¤´è¡”
  bio = "è¿™é‡Œå†™ä½ çš„ä¸ªäººç®€ä»‹ã€‚ä¾‹å¦‚ï¼šFocusing on academic tools development." # ç®€ä»‹
  
  # ä¸‹é¢é…ç½®ä½ çš„ç¤¾äº¤é“¾æ¥ (æŒ‰éœ€å¢åˆ )
  [[author.links]]
    icon = "github"
    href = "https://github.com/laujoe"
  
  [[author.links]]
    icon = "email" # å¯¹åº” mail å›¾æ ‡
    href = "mailto:your-email@example.com"

  [[author.links]]
    icon = "graduation-cap" # å­¦æœ¯å¸½å›¾æ ‡ï¼Œé€‚åˆæ”¾ Google Scholar
    href = "https://scholar.google.com/..."
