# -- 基础设置 --
baseURL = "https://blog.laujoe.top"
languageCode = "zh-cn"
defaultContentLanguage = "zh-Hans"
title = "我的学术博客"
theme = "congo"

# -- 全局性能与搜索设置 --
enableRobotsTXT = true
summaryLength = 0
timeZone = "Asia/Shanghai"
enableGitInfo = false

[pagination]
  pagerSize = 10


[outputs]
  home = ["HTML", "RSS", "JSON"]

# -- 渲染设置 (Congo 必须) --
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# -- 隐私与服务设置 --
[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true

# -- 文章页面设置 --
[params.article]
  showDate = true
  showLastMod = false

# -- Frontmatter 读取规则 --
[frontmatter]
  date = ["date", ":default"]
  lastmod = ["lastmod", ":default"]
  publishDate = ["publishDate", "date", ":default"]